## NumPy Array Attributes

In [2]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)
print(x1)  # One-dimensional array
print("\n")
x2 = np.random.randint(10, size=(3, 4))
print(x2)  # Two-dimensional array
print("\n")
x3 = np.random.randint(10, size=(1, 2, 3))  # Three-dimensional array
print(x3)
print(x3.shape)

[5 0 3 3 7 9]


[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


[[[8 1 5]
  [9 8 9]]]
(1, 2, 3)


## Array Indexing: Accessing Single Elements

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [3]:
x1

array([5, 0, 3, 3, 7, 9])

In [4]:
x1[0]

np.int64(5)

In [5]:
x1[4]

np.int64(7)

To index from the end of the array, you can use negative indices:

In [6]:
x1[-1]

np.int64(9)

In [7]:
x1

array([5, 0, 3, 3, 7, 9])

In [8]:
x1[-2]

np.int64(7)

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [9]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [10]:
a=5
#c=a*x2;
#print(c)
print("x2 before multiplication",x2)
x2*=a     #x2=x2*a
print(x2)

x2 before multiplication [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[15 25 10 20]
 [35 30 40 40]
 [ 5 30 35 35]]


In [11]:
print(x2)
x2[0, 0]

[[15 25 10 20]
 [35 30 40 40]
 [ 5 30 35 35]]


np.int64(15)

In [12]:
x2[2, 0]

np.int64(5)

In [13]:
print(x2)
x2[1, -3]

[[15 25 10 20]
 [35 30 40 40]
 [ 5 30 35 35]]


np.int64(30)

Values can also be modified using any of the above index notation:

In [14]:
print(x2)
x2[0, 0] = 12
print(x2)

[[15 25 10 20]
 [35 30 40 40]
 [ 5 30 35 35]]
[[12 25 10 20]
 [35 30 40 40]
 [ 5 30 35 35]]


Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [15]:
print(x1)
x1[0] = 3.14159  # this will be truncated!
x1

[5 0 3 3 7 9]


array([3, 0, 3, 3, 7, 9])

## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [16]:
y=np.arange(20)
print(y)
x = np.arange(1,20,3)   # from 1 to 20 in jumps of +3
x

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([ 1,  4,  7, 10, 13, 16, 19])

In [17]:
print(x)
#x[:5]  # first five elements, because 2nd parameter is the stopping size

[ 1  4  7 10 13 16 19]


In [18]:
x[5:]  # elements from 5th index

array([16, 19])

In [19]:
print(x)
x[4:5]  # middle sub-array    ingores error even when x[4:9] is given and displays the output

[ 1  4  7 10 13 16 19]


array([13])

In [20]:
print(x)
print(x[::2])  # every other element
x[::3]

[ 1  4  7 10 13 16 19]
[ 1  7 13 19]


array([ 1, 10, 19])

In [21]:
x[1::2]  # every other element, starting at index 1

array([ 4, 10, 16])

In [22]:
x[1::]

array([ 4,  7, 10, 13, 16, 19])

A potentially confusing case is when the ``step`` value is negative.
In this case, the defaults for ``start`` and ``stop`` are swapped.
This becomes a convenient way to reverse an array:

In [23]:
print(x[::-1])  # all elements, reversed
print(x)

[19 16 13 10  7  4  1]
[ 1  4  7 10 13 16 19]


In [24]:
x[5::-2]  # reversed every other from index 5

array([16, 10,  4])

### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [25]:
x2
print(x2)
x2[0:]      #start:stop:step

[[12 25 10 20]
 [35 30 40 40]
 [ 5 30 35 35]]


array([[12, 25, 10, 20],
       [35, 30, 40, 40],
       [ 5, 30, 35, 35]])

In [26]:
#x2[:2]   # from 0th row, display only 2 rows( from starting)
#x2[:3]   #  3 rows starting from 0th row
x2[:,2]   #from 0th row to all the rows, 3rd(index 2) column
x2[1:,2]  #from 1st row to all rows, 3rd(index 2)column
x2[:,[1,3]]     # from all rows, pick only 1st and 3rd rows
x2[1:]        # from 2nd row to the end

array([[35, 30, 40, 40],
       [ 5, 30, 35, 35]])

In [27]:
print(x2)
print("\n")
x2[1:]

[[12 25 10 20]
 [35 30 40 40]
 [ 5 30 35 35]]




array([[35, 30, 40, 40],
       [ 5, 30, 35, 35]])

In [28]:
x2[:,2]       #all rows, 3rd(index 2)column

array([10, 40, 35])

In [29]:
x2[:]

array([[12, 25, 10, 20],
       [35, 30, 40, 40],
       [ 5, 30, 35, 35]])

In [30]:
x2[1,:]
x2[[1,2],1:]    # 2 & 3rd row, from 2nd(index 1)column till end
x2[[1,2],:3]    # 2 & 3rd row, from 1st(index 0)column to 3 (counted) cloumns
x2[[1,2],::2]   # 2 & 3rd row, every alternative column

array([[35, 40],
       [ 5, 35]])

In [31]:
print(x2)
print("\n")
x2[[1,2],::2]       #[start:stop],[start:stop]:step
x2[::,:]    #print(x2) x2[0:] x2[0:5]  x2[0:,:]

[[12 25 10 20]
 [35 30 40 40]
 [ 5 30 35 35]]




array([[12, 25, 10, 20],
       [35, 30, 40, 40],
       [ 5, 30, 35, 35]])

In [32]:
x2[:,2]

array([10, 40, 35])

In [33]:
x2[:,[0,3]]     # all rows, 2nd(index -1)column and 4th(index 3) cloumn
#x2[1:,[1,3]]
#x2[2:,[1,3]]

array([[12, 20],
       [35, 40],
       [ 5, 35]])

In [34]:
x2[:2, :3]  # 1st-two rows (2 counted rows), three counted columns (1st-3 columns)

array([[12, 25, 10],
       [35, 30, 40]])

In [35]:
x2[:3, ::2]  # all rows, every other column

array([[12, 10],
       [35, 40],
       [ 5, 35]])

In [36]:
x2

array([[12, 25, 10, 20],
       [35, 30, 40, 40],
       [ 5, 30, 35, 35]])

Finally, subarray dimensions can even be reversed together:

In [37]:
print(x2)
print("\n",x2[::-1, ::])    #1st- reverses rows 2nd- reverses columns
x2[::-1,::-1]

[[12 25 10 20]
 [35 30 40 40]
 [ 5 30 35 35]]

 [[ 5 30 35 35]
 [35 30 40 40]
 [12 25 10 20]]


array([[35, 35, 30,  5],
       [40, 40, 30, 35],
       [20, 10, 25, 12]])

#### Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

In [38]:
print(x2[:, 0])  # first column of x2

[12 35  5]


In [39]:
print(x2[0, :])  # first row of x2

[12 25 10 20]


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [40]:
print(x2[0])  # equivalent to x2[0, :]

[12 25 10 20]


### Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:

In [41]:
print(x2)

[[12 25 10 20]
 [35 30 40 40]
 [ 5 30 35 35]]


Let's extract a $2 \times 2$ subarray from this:

In [42]:
x2_s = x2[:2, :2]
print(x2_s)

[[12 25]
 [35 30]]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [43]:
x2_s[0, 0] = 100
print(x2_s)

[[100  25]
 [ 35  30]]


In [44]:
print(x2)       #changes made in sub array x2_sub is reflected in the main array

[[100  25  10  20]
 [ 35  30  40  40]
 [  5  30  35  35]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [45]:
print(x2)
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[100  25  10  20]
 [ 35  30  40  40]
 [  5  30  35  35]]
[[100  25]
 [ 35  30]]


If we now modify this subarray, the original array is not touched:

In [46]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42 25]
 [35 30]]


In [47]:
print(x2)

[[100  25  10  20]
 [ 35  30  40  40]
 [  5  30  35  35]]


## Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [48]:
grid = np.arange(1,10).reshape((1,9))
print(grid)
print(grid.shape)
print(grid.ndim)

[[1 2 3 4 5 6 7 8 9]]
(1, 9)
2


Note that for this to work, the size of the initial array must match the size of the reshaped array.
Where possible, the ``reshape`` method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

In [49]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))
x.ndim

1

In [50]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [51]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [52]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

In [53]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z=np.concatenate([y, x])
print(z)

[3 2 1 1 2 3]


You can also concatenate more than two arrays at once:

In [54]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


It can also be used for two-dimensional arrays:

In [55]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
#reshape it as row matrix


In [56]:
# concatenate along the first axis
g1=np.concatenate([grid, grid])
print(g1)
print(g1.ndim)
print(g1.shape)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
2
(4, 3)


In [57]:
# concatenate along the second axis (zero-indexed)
x3 = np.random.randint(10, size=(2,2, 3))  # Three-dimensional array
print(x3)
print(x3.ndim)
print(x3.shape)
#reshape it as row matrix with 1x60
z=np.concatenate([x3, x3],axis=2)
print(z)
print(z.ndim)
print(z.shape)

[[[4 3 0]
  [3 5 0]]

 [[2 3 8]
  [1 3 3]]]
3
(2, 2, 3)
[[[4 3 0 4 3 0]
  [3 5 0 3 5 0]]

 [[2 3 8 2 3 8]
  [1 3 3 1 3 3]]]
3
(2, 2, 6)


In [58]:
x4 = np.random.randint(10, size=(2,4,2,3))
print(x4)
print(x4.ndim)
print(x4.shape)
print(x4.size)
print("\n","concatenated matrix is")
z=np.concatenate([x4, x4],axis=2)
print(z)
print(z.ndim)
print(z.shape)
print(z.size)
#reshape it to row matrix

[[[[3 7 0]
   [1 9 9]]

  [[0 4 7]
   [3 2 7]]

  [[2 0 0]
   [4 5 5]]

  [[6 8 4]
   [1 4 9]]]


 [[[8 1 1]
   [7 9 9]]

  [[3 6 7]
   [2 0 3]]

  [[5 9 4]
   [4 6 4]]

  [[4 3 4]
   [4 8 4]]]]
4
(2, 4, 2, 3)
48

 concatenated matrix is
[[[[3 7 0]
   [1 9 9]
   [3 7 0]
   [1 9 9]]

  [[0 4 7]
   [3 2 7]
   [0 4 7]
   [3 2 7]]

  [[2 0 0]
   [4 5 5]
   [2 0 0]
   [4 5 5]]

  [[6 8 4]
   [1 4 9]
   [6 8 4]
   [1 4 9]]]


 [[[8 1 1]
   [7 9 9]
   [8 1 1]
   [7 9 9]]

  [[3 6 7]
   [2 0 3]
   [3 6 7]
   [2 0 3]]

  [[5 9 4]
   [4 6 4]
   [5 9 4]
   [4 6 4]]

  [[4 3 4]
   [4 8 4]
   [4 3 4]
   [4 8 4]]]]
4
(2, 4, 4, 3)
96


For working with arrays of mixed dimensions, it can be clearer to use the ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) functions:

In [59]:
x = np.array([1, 2, 3])
print(x.ndim)
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
print(grid.ndim)
#np.concatenate(x,grid)

# vertically stack the arrays
np.vstack([x, grid])


1
2


array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [60]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

In [61]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 2])  #1st 3 ele of 5 in x1, remaining in x2 of 5, rest in x3
print(x1, x2, x3)

[1 2 3] [] [ 3 99 99  3  2  1]


Notice that *N* split-points, leads to *N + 1* subarrays.
The related functions ``np.hsplit`` and ``np.vsplit`` are similar:

In [62]:
grid = np.arange(16).reshape((4, 4))
grid
print(grid.shape)

(4, 4)


In [63]:
upper, lower = np.vsplit(grid, [2]) # 2nd parameter is the number of rows to include in the split
print(upper)
print("lower array is")
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
lower array is
[[ 8  9 10 11]
 [12 13 14 15]]


In [64]:
print(grid,"\n")
left,right = np.hsplit(grid, [2])
print(left)
print(right)
#x5=grid;print(x5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
